### ISSUE TITLE
swagger model builder craps out in case of a `HEAD` defined in route

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#102]
https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala#L39

https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/models.scala#L191

`wordnik` for `Path` is also missing the `HEAD` request in methods.  

For one, we should add a `default` to guard the `match` of method, and probably we should extend the `wordnik` `Path` class to add the `HEAD` method, though I am not sure if `swagger` can work with `HEAD` request.

**Comment by bryce-anderson** [comment]
Agreed. It looks like [`swagger-core` does support `HEAD` requests](https://github.com/swagger-api/swagger-core/blob/fe2e545806a1c129ce8405c208088452766fb46e/modules/swagger-models/src/main/java/io/swagger/models/Path.java#L18).

**Comment by bryce-anderson** [comment]
Closed by commit 9e746645f1794f974e550ab1d2112c4a16a33654.
