### ISSUE TITLE
Scaladoc shows left frame, not right

### ISSUE THREAD

**Issue by rossabaker** [http4s/rho#119]
```
Refused to display 'http://rho.http4s.org/api/0.9/package.html' in a frame because it set 'X-Frame-Options' to 'DENY'.
```

The header is apparently [not something we can change](http://stackoverflow.com/questions/17012727/how-to-set-the-x-frame-options-in-a-content-hosted-by-github).  @peterbecich reports that [this Chrome plugin](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe?hl=en-US) is a workaround.  Still, would be nice if our docs didn't require a plugin.

**Comment by jarben** [comment]
This used to work until few hours ago, being reported by many, hopefully GitHub reverts this header asap.. 

https://twitter.com/mrdoob/status/687210451617333248
https://www.reddit.com/r/Trimps/comments/40qafc/bug_not_working_on_kongregate/
..

**Comment by bryce-anderson** [comment]
Looks like this is working once again.

**Comment by refried** [comment]
What a weird header to even exist.
