### ISSUE TITLE
incompatibility of Scala 2.11.8

### ISSUE THREAD

**Issue by shengc** [http4s/rho#136]
Is it a known issue to the Lightbend ? If so, can you please provide the ticket number tracking the issue ? Our work has been stuck at 2.11.7 because of this :-(

**Comment by bryce-anderson** [comment]
I don't know if it is or not. @rossabaker suggested bisecting scalac between 2.11.7 and 2.11.8, but that has been pretty low on my priority list.

**Comment by rossabaker** [comment]
I don't think it's been minimized to the point that it is actionable by Lightbend.  @reactormonk was thinking about a bisector script for another problem.  He wanted a script that returned 0 or not to show the pattern.  Is that bisection still a relatively easy thing to write, as slow as it might be to run?

**Comment by shengc** [comment]
I have been able to narrow down the issue to the following,

```scala
  object route extends RhoService {
    GET / "root" |>> { () ⇒ Ok("Hello") }
  }

  object route2 extends RhoService {
    val ok = Ok("Hello")
    GET / "root" |>> { () ⇒ ok }
  }
```

so with 2.11.8 `route` compiles, `route2` _does not_, but both of them compiles in 2.11.7. I had tried to turn on the implicit log to see how compiler resolves the implicits, but the output is sort of overwhelming to me. Can you pick up from here to see if this can be further minimized to something that Lightbend can act on ?

**Comment by shengc** [comment]
what is weird is just by putting `implicitly[EntityEncoder[String]]`in context will solve all compile errors. If I remove the `implicit` keyword from `charSequenceEncoder`, compile errors go away except for the ones that does not take type parameter, such as `CONTINUE`, `REDIRECT`, etc. I think the implicit instances of `EntityEncoder` do have ambiguities from the perspective of 2.11.8, and some are not just found yet.

**Comment by rossabaker** [comment]
I remember Bryce having a very difficult time organizing the priorities of the implicits in EntityEncoder to make it work.

This is unlikely, but I wonder if it does better with the SI2712-fix compiler plugin?  I hit some cases on the cats branch where implicits were ambiguous  and the plugin made it find the expected one.  I don't think that will work here, because I don't think this is an issue of kinds, but it might be worth a try.

**Comment by shengc** [comment]
tried typelevel scalac, with SI-2712 fix and SIP-23 enabled, still the example project is failed to compile. For now, the workaround is to bring `implicitly[EntityEncoder[String]]` into scope, and all compile errors would magically be resolved. This is the best I can offer at the moment. Hopefully someone can revisit and actually fix this issue later.

**Comment by bryce-anderson** [comment]
@rossabaker and I discussed this briefly and think you're probably on to
something: in the past, somehow the implicit EntityEncoders were becoming
ambiguous (at least in the compilers eyes) and making some changes in
http4s were required. That may be the case again. Specifically,
CharSequence may be a problem and maybe it should go: it's really not that
useful anyway.

I'll take a look when I can, but this week is rapidly getting away from me
so I can't promise that it will happen soon. Thanks for reducing the
problem, that is a huge head start.

**Comment by bryce-anderson** [comment]
So I spent the evening compiling scalac over and over again and it turns out that this is the commit that breaks rho: https://github.com/scala/scala/commit/5db2d831a79f6ea3.
Relevant comment in the commit source suggests a change in behavior to looking up implicit members in the package, rather than package object when doing wildcard imports.

**Comment by bryce-anderson** [comment]
I've filed a bug in the scalac JIRA system: https://issues.scala-lang.org/browse/SI-9928

**Comment by shengc** [comment]
Thank you for summarizing and reporting the issue ... that commit message suggests it was an improvement for IDE, i.e., the presentation compiler? Anyway, hopefully Lightbend can take a look at it soon.

**Comment by etorreborre** [comment]
@bryce-anderson I got the `examples/src/main/scala/com/http4s/rho/hal/plus/swagger/demo/RestService.scala` file to compile with scala 2.11.8 by adding this import:
```scala
object rh extends Http4s with ResultSyntaxInstances
import rh._
```

**Comment by bryce-anderson** [comment]
Oh, very interesting. I'll have to take a closer look at that. I believe @shengc found that importing a few implicits from http4s made his example work (please correct me if I'm wrong, that was a while ago), so perhaps that is related. If you find anything new, I'm totally interested!

Thanks for the update.

**Comment by zarthross** [comment]
@etorreborre Turns out you don't need the `ResultSyntaxInstances` for that to work.

**Comment by zarthross** [comment]
Turns out if you follow the inheritance tree for Http4s, its actually the `EntityEncoderInstances` that you need to import for @etorreborre's case to work.  So you could get the same effect with `import EntityEncoder._`.

**Comment by zarthross** [comment]
Alright, so if you make `RhoService` extend `EntityEncoderInstances` like `Http4s` does via `Http4sInstances`, then everything builds and test pass (at least on my machine)

**Comment by etorreborre** [comment]
@zarthross thanks for minimizing it :-). Your last comment makes me think that we could create a small PR based on this and we could test it on both 2.11.8 and 2.12.1.

**Comment by zarthross** [comment]
I'm working on that right now!

**Comment by zarthross** [comment]
Can we close this now?
