### ISSUE TITLE
Custom field serializers don't work with Option(al) fields

### ISSUE THREAD

**Issue by phile314-isska** [http4s/rho#140]
Example:
<pre>
  val swaggerFormats = DefaultSwaggerFormats.withFieldSerializers({
    case x if x =:= typeOf[DateTime] => AbstractProperty(`type`="string", format = Some("date-time"))
  })
</pre>
JSON Response Case Class:
<pre>
case class Project(
                    id:Option[Long],
                    name:String,
                    modified: Option[DateTime],
                    created: DateTime)
</pre>
Generated Swagger:
<pre>
{
"swagger":"2.0",
"info":{"version":"1.0.0","title":"My API"},
"paths":{
  "/projects":{
    "get":{
      "tags":["projects"],
      "summary":"List of all projects belonging to the authenticated user.",
      "operationId":"getProjects",
      "produces":["application/json"],
      "responses":{
        "200":{
          "description":"OK",
          "schema": {
            "type":"array","items":{"$ref":"#/definitions/Project"}
          }
        }
      }
    }
  }
},
"definitions":{
  "Project":{
    "required":["created","description","name"],
    "properties":{
      "name":{"type":"string"},
      "description":{"type":"string"},
      "id":{"type":"integer","format":"int64"},
      "modified":<b>{"type":"DateTime","description":"org.joda.time.DateTime"}</b>,
      "created":<b>{"type":"string","format":"date-time"}</b>
      },
    "description":"Project"
    }
  }
}
</pre>

**Comment by bryce-anderson** [comment]
Have you had a chance to check PR #139?

**Comment by bryce-anderson** [comment]
@phile314-isska, see #141. I'd appreciate you testing it with your use case before I merge it.

**Comment by phile314-isska** [comment]
Just tested it, works perfectly :+1:

**Comment by bryce-anderson** [comment]
Fixed by #141.
