### ISSUE TITLE
pathVar[String] does not URL decode by default.

### ISSUE THREAD

**Issue by zarthross** [http4s/rho#150]
It would appear the StringParser for type String for pathVar doesn't url decode the strings by default.  Was this expected behavior?  If not, can we correct that or at least have some way to optionally specify automatic decoding?

**Comment by bryce-anderson** [comment]
I would say it is likely an oversite. I don't know how many people would be dependent on this behavior by now, so maybe they should chime in. Folks that come to mind are @etorreborre and @jcranky.
I'm open to changing the default so long as it doesn't cause tremendous pain for others.

**Comment by bryce-anderson** [comment]
For those interested, I believe the problem is right here: https://github.com/http4s/rho/blob/a3091413a371b5e7d6d8e9175d8514cbbd1da21f/core/src/main/scala/org/http4s/rho/bits/PathTree.scala#L68. We should probably be URL decoding the individual elements.

**Comment by zarthross** [comment]
Added PR#152 to hopefully resolve this issue.

**Comment by zarthross** [comment]
Issue address by #152
