### ISSUE TITLE
`ServiceBuilder.toService` should allow providing a custom `NotFound` response

### ISSUE THREAD

**Issue by shengc** [http4s/rho#156]
And `RouteResult.toResponse` should use that in place of deprecated `HttpService.notFound` if it were provided (e.g., `Response.fallthrough`). The benefit is that one can chain up `Fallthrough`-ed services in a much more straightforward way. 

On a separate note, `HttpService.notFound` has been deprecated. Why the compiler does not penalize the warning into an error? I have not taken a look at the compiler flags, but we should turn on `-Xfatal-warnings` regardless, right ?

**Comment by bryce-anderson** [comment]
Agreed on all accounts. And yes, we should probably be more strict on warnings. There is plenty of cleanup to do in rho: it feels like the project is on the tail end of the heavy construction phase and now getting into the refinement phase.

**Comment by bryce-anderson** [comment]
Are you using `ServiceBuilder` directly? I just put up a PR that does a few changes to it, #160, that may be important to you. In my minds eye it was rarely if ever used directly so that PR attempts to hide it to some degree.

How do you envision the custom `NotFound` being passed in? `Request => Task[Response]`? I'm just trying to figure out why this is not a case that could be addressed with the standard http4s tools, although all this Fallthrough business seems to be in flux right now: https://github.com/http4s/http4s/pull/810.

**Comment by shengc** [comment]
I am just thinking out loud. The change could be as simple as follows,

```scala
final def toService(filter: RhoMiddleware = identity, notFound: Task[Response] = Response.notFound): HttpService = 
  foldServices(internalRoutes.result(), filter, notFound)

def foldServices(routes: Seq[RhoRoute.Tpe], filter: RhoMiddleware = identity, notFound: Task[Response] = Response.notFound) = {
      val tree = filter(routes).foldLeft(PathTree()){ (t, r) => t.appendRoute(r) }
      Service.lift { req => tree.getResult(req).toResponse(notFound) }
}

sealed trait RouteResult[+T] {
    final def toResponse(notFound: Task[Response] = Response.notFound)(implicit ev: T<:<Task[Response]): Task[Response] = this match {
      case SuccessResponse(t) => ev(t)
      case NoMatch            => notFound
      case FailureResponse(r) => r.toResponse
    }
}
```

I indeed am not quite comfortable with the current implementation of Fallthrough logic. As I mentioned in the related PR, using a dedicated `Response` object to drive the Fallthrough logic potentially makes the middleware manipulating the Response` fall into the cracks.

**Comment by zarthross** [comment]
Http4s 0.19 has a new mechanism for dealing with closing  routes with a custom not found response.  Rho 0.19 will support this as well.  Feel free to reopen if it isn't satisfactory then.
