### ISSUE TITLE
`|>> { .. }` should be thunk

### ISSUE THREAD

**Issue by reactormonk** [http4s/rho#174]
@ import $ivy.`org.http4s::rho-swagger:0.16.0a` 
    @ import org.http4s.rho._
    @ new RhoService { GET / "foo" |>> { println("hit"); Ok("foo") } } 
    hit

Pretty sure the response clause should be thunked.

**Comment by bryce-anderson** [comment]
Its been a while, but I recall this being an intentional choice on my part. If you want thunk like behavior, `Task` provides that for you.

**Comment by reactormonk** [comment]
I didn't expect that, since any other code in that context is executed as a thunk, so I expected this one to be that way too.

**Comment by bryce-anderson** [comment]
I believe the right hand side of the `|>>` operator is always evaluated eagerly. I'm guessing that you are referring to routes who's actions are a FunctionN, which reminds me: another good alternative is to use a Function0:
```scala
scala> new RhoService {
     | GET / "foo" |>> { () => println("hit"); Ok("foo") }
     | }
res2: org.http4s.rho.RhoService = RhoService(Vector(RhoRoute(Router(GET,PathAnd(PathMatch(),PathMatch(foo)),EmptyRule),Action(Set(StatusAndType(200 OK,java.lang.String)),Set(MediaType(text/plain)),<function2>))))
```
