### ISSUE TITLE
how to use with argonaut?

### ISSUE THREAD

**Issue by neilbacon** [http4s/rho#175]
I've been using the http4s DSL with Argonaut and I'd like to switch to rho, but I can't figure out how to define the HListToFunc that seems to be required.

To get |>> to compile in (where NodeQuery is a simple case class with an argonaut.CodecJson defined):

    POST / "node" ^ jsonOf[NodeQuery] |>> { q: NodeQuery =>

I need:

    val responseEncodings = Set(MediaType.`application/json`)
    type NQShapeless = shapeless.::[NodeQuery, shapeless.HNil]
    implicit val hltf = new HListToFunc[NQShapeless, NodeQuery => scalaz.concurrent.Task[Ok.T[Json]]] {
      override def toAction(f: NodeQuery ⇒ scalaz.concurrent.Task[Ok.T[Json]]): Action[NQShapeless]
      = ???  // Action(resultInfo: Set[ResultInfo], responseEncodings, act: (Request, NQShapeless) => Task[Response])
    }

How do I get an appropriate `resultInfo` & `action`?

**Comment by neilbacon** [comment]
oh, just read this is a blocker: scalaVersion := "2.11.8"

**Comment by zarthross** [comment]
@neilbacon has this been resolved for you?  Can I close this issue?

**Comment by neilbacon** [comment]
Sure, but maybe document scala version compatibility?

**Comment by zarthross** [comment]
Noted in the [wiki](https://github.com/http4s/rho/wiki/Versions)
