### ISSUE TITLE
Should `SwaggerFormats` be sealed?

### ISSUE THREAD

**Issue by changlinli** [http4s/rho#182]
It looks like the only thing that extends `SwaggerFormats` is `DefaultSwaggerFormats`. Could you just keep the `DefaultSwaggerFormats` object around (and probably rename it to just `SwaggerFormats`) and remove the trait? Or perhaps open up the trait to extension?

As it stands, if I want to customize some of the Swagger output of my models, I'm not sure quite sure whether I'm supposed to be using `DefaultSwaggerFormats` and then calling `withSerializers` or whether there was some oversight and I'm supposed to be extending `SwaggerFormats` directly.

**Comment by bryce-anderson** [comment]
I think you're right: the `SwaggerFormats` trait should probably be turned into a final case class with fields for the serializers and field serializers. If you're interested, a PR for this would almost certainly be accepted. 😄

**Comment by changlinli** [comment]
Well since you asked so nicely... :). Here's a first pass.
