### ISSUE TITLE
Missing implicits error

### ISSUE THREAD

**Issue by eklavya** [http4s/rho#188]
Hi, I am facing a weird issue where the RhoService only compiles if a particular handler is at the top and fails otherwise.

I have created a test case here: https://github.com/eklavya/RhoTestCase

Please let me know what I am doing wrong here.

**Comment by eklavya** [comment]
Moving imports from inside RhoService to top level fixes the problem.

**Comment by jcranky** [comment]
@eklavya should we close this or is this still a problem with the current version ?

**Comment by eklavya** [comment]
I didn't try the same thing but moving imports to the top did solve this. I think we can close this.
Maybe in the examples the imports should be shown at the top.

**Comment by jcranky** [comment]
Sounds good, PR coming :)
