### ISSUE TITLE
Travis deployment is broken

### ISSUE THREAD

**Issue by rossabaker** [http4s/rho#192]
https://travis-ci.org/http4s/rho/jobs/281292952

I don't know what's in deployprep to try to fix whatever keys got ripped asunder.  I can fix this, but I probably can't fix it in the same way.

**Comment by bryce-anderson** [comment]
We're back: https://travis-ci.org/http4s/rho/jobs/283991634

**Comment by bryce-anderson** [comment]
We're not back... https://travis-ci.org/http4s/rho/jobs/251580095

**Comment by bryce-anderson** [comment]
Okay, its really fixed now: https://travis-ci.org/http4s/rho/builds/283996526
