### ISSUE TITLE
Release a http4s-0.16 compatible version

### ISSUE THREAD

**Issue by wongelz** [http4s/rho#204]
Can we release a version of rho compatible with http4s-0.16. This is the final scalaz version of http4s, so I imagine a lot of people will be stuck on it for a while.

Of the versions of rho on maven central, 0.16.2 was built against http4s-0.15, then the next version 0.17 jumps to http4s-0.17.

**Comment by rossabaker** [comment]
Interesting. I didn't realize that had been skipped.

Volunteers to prepare a branch?  Suggestions on version number?

**Comment by jcranky** [comment]
Done, right?

**Comment by bryce-anderson** [comment]
Yes, I believe so.
