### ISSUE TITLE
Release a http4s-0.18 compatible version

### ISSUE THREAD

**Issue by anne-nelson** [http4s/rho#207]
Are you going to release a new version compatible with http4s-0.18 anytime soon?

**Comment by jcranky** [comment]
I'm working on that here: https://github.com/http4s/rho/pull/193

**Comment by jcranky** [comment]
I guess we can now release, right @bryce-anderson  ? :) Specially after @eklavya report that he migrated to latest snapshot without issues

**Comment by ChristopherDavenport** [comment]
We have the milestone release. We have the UUID/Date components which we could ship into an M2. I think its wise we solve #218 because I think it will cause a lot of pain to normal use cases to folks who don't use specific imports. Then we should address which other issues we need to take care of to go from milestones to a full release.

**Comment by eklavya** [comment]
If anything reduces the implicit fragile ness I would say wait for it. Till then local builds will do.

**Comment by bryce-anderson** [comment]
I don't have a strong feeling about it one way or the other, but I suspect #218 is a simple fix other than it will require some pretty difficult debugging. I think @ChristopherDavenport's plan is pretty solid.

**Comment by jcranky** [comment]
Works for me :)

**Comment by ChristopherDavenport** [comment]
I think we're ready to cut an 0.18.0 without any objections. Does anyone have any issues they'd like to wait on, or should I cut this today?

**Comment by jcranky** [comment]
fine for me

**Comment by bryce-anderson** [comment]
cut it.

**Comment by loicknuchel** [comment]
Hello, nice ;)
Seems, the release is done.
It should be nice to update https://github.com/http4s/rho/wiki/Versions also

**Comment by ChristopherDavenport** [comment]
Done and done. 👍
