### ISSUE TITLE
Idiomatic way of evaluating and handling errors

### ISSUE THREAD

**Issue by wookievx** [http4s/rho#229]
I have recently picked-up rho. I would like to know is there an "Idiomatic" way to deal with the following case: 

- I have domain specific function returning some value
- There are some hierarchy of errors i need to evaluate accordingly and respond to the client with proper status code
- I would like to be able to retain type information about errors/return types that will allow to generate documentation for my API

I tried to figure it out myself, but ultimately i failed. The following code is my MVC of my attempt:
```scala
class Demonstrator[F[+_]: Effect] {
  import cats.syntax.applicativeError._

    //not compiling
  val serviceFc = new RhoService[F] {
    val logicResult: F[String] = ???
    GET / "some-resource" / pathVar[Long] |>> { id: Long =>
      val resultT = logicResult.attemptT
      def handleError(error: Throwable) = {
        error match {
          case t if t.getMessage.startsWith("A") =>
            BadRequest("Bad request")
          case t: RuntimeException =>
            InternalServerError("Something went wrong")
        }
      }

      resultT.fold(
        handleError,
        Ok(_)
      )
    }
  }
  //compiling but missing some information when documentation is generated
  val serviceFc = new RhoService[IO] {
    val logicResult: IO[String] = ???
    GET / "some-resource" / pathVar[Long] |>> { id: Long =>
      val resultT = logicResult.attemptT

      def handleError(error: Throwable) = {
        error match {
          case t if t.getMessage.startsWith("A") =>
            BadRequest("Bad request")
          case t: RuntimeException =>
            InternalServerError("Something went wrong")
        }
      }

      resultT.fold(
        handleError,
        Ok(_)
      )
    }
  }
}
```
If there is already a way to achieve something similar, could someone point it out?

**Comment by wookievx** [comment]
I found one source of my compilation problems:
`def handleError(error: Throwable)`
Has in fact type F[Result[F,...]]
Basically `flatten` solves my problem

**Comment by jmcardon** [comment]
use `handleErrorWith`

**Comment by nightscape** [comment]
Hi @wookievx, @jmcardon,

would you be so kind to post a working example here?
The best thing I could come up so far is something like this
```scala
for {
  item <- findItem(1)
  response <- Ok(item).widen[Result.BaseResult[F]].handleErrorWith(e => NotFound(Error(e.toString)))
} yield response
```
where `findItem` returns a result in a `F : Effect`.
But that messes up the Swagger documentation completely (there's no `responses` key in the corresponding hash)...

**Comment by wookievx** [comment]
`widen[Result.BaseResult[F]]` is source of your problem, you are erasing all type information about response, you should be able to compile and run your code without it and it should work just fine.

Checkout the following example (avoided imports, there is probably Effect needed and applicativeError syntax in scope, but it's just a detail):
```scala
val logicResult: F[String] = ???
      GET / "some-resource" / pathVar[Long] |>> { id: Long =>
        val resultT = logicResult.attemptT

        def handleError(error: Throwable) = {
          error match {
            case t if t.getMessage.startsWith("A") =>
              BadRequest("Bad request")
            case t: RuntimeException =>
              InternalServerError("Something went wrong")
          }
        }

        resultT.fold(
          handleError,
          Ok(_)
        )
      }
```
Now error handling can be separated from the "main flow", and you could easily substitute Strings with your domain classes, and resulting type of the method should carry information about them (what status code results with what type of data)

**Comment by zsluedem** [comment]
@wookievx 
Got some problems with your example
```
[error] No HListToFunc instance found. 
[error]   Most likely no ResultMatcher instance is available for the return type of 
[error]     (() => F[F[_ >: this.Ok.T[CustomType] with this.BadRequest.T[String] <: org.http4s.rho.Result[F,Nothing,Nothing,Nothing,Nothing,coop.rchain.node.api.WebApi.ApiStatus,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,String,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing]]]). 
[error]   This can be caused by a lack of a matching EntityEncoder.
[error]     GET / "status" |>> { () =>
```
