### ISSUE TITLE
Keep on the lookout for swagger-core 2.0 artifacts

### ISSUE THREAD

**Issue by bryce-anderson** [http4s/rho#29]
The swagger 2.0 spec is out, and the jars we need to integrate it should be close behind. We need to keep on the lookout, I want to get this done as soon as possible.

**Comment by bryce-anderson** [comment]
### Update
The java swagger implementation is coming along slowly [here](https://github.com/swagger-api/swagger-core/tree/develop_2.0) and its [looking like there won't be a scala specific version](https://groups.google.com/forum/#!searchin/swagger-swaggersocket/scala/swagger-swaggersocket/hkYc03mO15I/YuVQXdKySPkJ). Perhaps that for the best as it may be a bit more difficult to implement using the java api, but it should be more stable.

**Comment by before** [comment]
We could ask @casualjim if he plans to upgrade **swagger-scala** to version 2.0, right?

**Comment by bryce-anderson** [comment]
In the [second link](https://groups.google.com/forum/#!searchin/swagger-swaggersocket/scala/swagger-swaggersocket/hkYc03mO15I/YuVQXdKySPkJ) (and his post may no longer be accurate) @casualjim states that its unlikely there will be a scala specific version.

**Comment by before** [comment]
Sorry, have mentioned it too late. Why would we need the Java-based Swagger API and could **swagger-core** be enough for our purpose?

**Comment by bryce-anderson** [comment]
Sorry, I didn't describe the situation clearly. When I said we should use the java-api, I mean't swagger-core, which is written in java.

**Comment by before** [comment]
Okay, thank you for clarifying it.

**Comment by bryce-anderson** [comment]
I tested the latest master of swagger-ui (its pretty easy, just clone the repo and point yourself to the dist/index.html for a working swagger-ui) and it appears that 2.0 is working enough to consider migrating. The only waiting piece is now swagger-core, which may actually be usable, I just don't know.

**Comment by bryce-anderson** [comment]
Artifacts are out. I"m closing this and opening an 'upgrade to swagger-2.0' issue.
