### ISSUE TITLE
Swagger endpoints ordering

### ISSUE THREAD

**Issue by vglushak** [http4s/rho#299]
I’ve noticed swagger is displaying endpoint in no particular order (it’s definelty not alphabetical nor the way how they defined in file). 
Is there particular way to control order?

**Comment by zarthross** [comment]
Looks like the `Swagger-modules` default is to use a `LinkedHashMap` so should preserve order, but Rho is using a simple Scala `Map` so we are loosing our key order.  If we change Rho to use a `ListMap` in a few key places we should be able to correct the order preservation.

**Comment by zarthross** [comment]
Fixed with #303
