### ISSUE TITLE
Feature request: Allow customizing tags for generated operations

### ISSUE THREAD

**Issue by danxmoran** [http4s/rho#314]
The models builder [currently defaults](https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala#L232) to using the first segment of an operation's path as its tag. Those tags are used as headings by the Swagger UI to group related routes together. My team follows a pattern of using an `/api` prefix for everything other than status checks, so we end up with one big block of routes in the UI:
![Screen Shot 2019-05-01 at 1 56 46 PM](https://user-images.githubusercontent.com/2755881/57032699-024b9200-6c19-11e9-867c-dc60e7683a29.png)
Ideally, we'd like to be able to override the tags to manually group things ourselves.

I'd be happy to contribute this change, as long as it hasn't been left out for a reason.

**Comment by zarthross** [comment]
I agree, you should be able override those tags and as far as I know there isn't a particular reason why, just never added as a feature.  I imagine tagging would work similar to the way the description is added.

If you want to contribute a patch, I'll be happy to review it and get it added in.

**Comment by danxmoran** [comment]
Any preferences on syntax? The convention seems to be:
* Symbolic operator
* Extension method on a non-Rho construct, with `RhoRoutes` on the RHS.
```scala
// We have:
description ** route
auth ^^ route

// Add a new?
tags @@ route
```

... But without the convention, I'd probably add a new method on `RouteBuilder`:
```scala
route.withTags(tags)
```
