### ISSUE TITLE
swagger-ui only show the first service's routes

### ISSUE THREAD

**Issue by logosmjt** [http4s/rho#364]
In "org.http4s" % "rho-swagger_2.12" % "0.19.0", 
BlazeServerBuilder[IO].bindHttp(port, "0.0.0.0") .withHttpApp(service1 <+> service2)...
swagger-ui only show routes of service1, does not show another.

**Comment by logosmjt** [comment]
service1 works with auth
service2 doesn't work with auth

**Comment by zarthross** [comment]
@logosmjt Swagger is generated when you convert a `RhoRoutes` to an `Http4sRoutes`, and there is no way to combine swaggers at present. So when you generate `service1` and `service2` into `Http4sRoutes` the swagger route gets overridden.  

I have some ideas in mind to correct this, they are WIP.

**Comment by logosmjt** [comment]
@zarthross I tried " route1.and(route2).and(route3).toRoutes(...)", and it went well.
