### ISSUE TITLE
Provide example using the Swagger UI Webjar

### ISSUE THREAD

**Issue by etspaceman** [http4s/rho#366]
Hello there - 

I was going through your examples when setting up a project of my own, and I noticed that you are including the swagger-ui distribution directly in the project's resources files. 

Considering http4s has support for webjars, and the swagger-ui is distributed in its own webjar, we should be possible to provide an example that uses said webjar.

**Comment by zarthross** [comment]
Thanks for opening an issue.  I agree we should at least provide an example using a webjar... what would probably be even better is a module that just hosts the swagger-ui from a webjar to reduce boilerplate for users.
