### ISSUE TITLE
Where is RhoService?

### ISSUE THREAD

**Issue by fancellu** [http4s/rho#406]
I see it in the docs, tutorial

Can't see it in rho-swagger 0.20.0, or in the source

**Comment by rossabaker** [comment]
I think it's called `RhoRoutes` now, corresponding to http4s' move from `HttpService` to `HttpApp` and `HttpRoutes`, and the docs haven't fully caught up.

**Comment by zarthross** [comment]
Ross is correct.  I've updated the wiki and put in a note to look at the [Rho Examples Project](https://github.com/http4s/rho/tree/master/examples/src/main/scala/com/http4s/rho/swagger/demo) for the most up to date examples.
