### ISSUE TITLE
Release v0.21.0 with swagger webjar implementation

### ISSUE THREAD

**Issue by adamtrousdale** [http4s/rho#432]
Hi there, can v0.21.0 be released in its current state? I would like to use the swagger webjar functionaility

**Comment by zarthross** [comment]
@adamtrousdale I will make some time on Friday to cut a release.  Thanks for the reminder!

**Comment by zarthross** [comment]
Release v0.21.0-RC1 should be on its way to maven central.

See https://github.com/http4s/rho/runs/837771442
