### ISSUE TITLE
Simple or-path produces incorrect tags

### ISSUE THREAD

**Issue by mcenkar** [http4s/rho#448]
Hi,

When using simple or-path:

`GET / ("foo" || "bar") |>> { () => "Hello!" }`

following `swagger.json` is produced:

```
{
  "paths": {
    "/foo": {
      "get": {
        "tags": [
          "foo",
          "bar"
        ],
        "operationId": "getFoo",
        "produces": [
          "text/plain"
        ]
      }
    },
    "/bar": {
      "get": {
        "tags": [
          "foo",
          "bar"
        ],
        "operationId": "getBar",
        "produces": [
          "text/plain"
        ]
      }
    }
  }
}
```

`/foo` path gets `bar` tag and `/bar` path gets `foo` tag which leads to unnecessary entries in swagger ui:

![image](https://user-images.githubusercontent.com/11230749/92688620-f5c36780-f33d-11ea-8ab5-ae46406b86d0.png)

I would expect single tags on both routes.

Also if you specify tag yourself:

`  "mytag" @@ GET / ("foo" || "bar") |>> { () => "Hello!" }`

it ends up there twice:

```
{
  "/foo": {
    "get": {
      "tags": [
        "mytag",
        "mytag"
      ],
      "operationId": "getFoo",
      "produces": [
        "text/plain"
      ]
    }
  }
}
```

**Comment by zarthross** [comment]
Fixed in #454
