### ISSUE TITLE
Body parameters are not being generated 

### ISSUE THREAD

**Issue by kryptt** [http4s/rho#52]
#50 describes thrown exceptions when attempting to build HttpServices with body parameters. 
Currently it is possible to build them, although the generated swagger api does not correctly expose them.

**Comment by bryce-anderson** [comment]
This is a subproblem of #53, the upgrade to swagger 2.0, and will certainly be addressed there.

**Comment by bryce-anderson** [comment]
Is this fixed? I think this is a stale bug. The upgrade to swagger-2.0 is complete thanks in large part to @cencarnacion.

**Comment by kryptt** [comment]
Yeah, I believe this is a stale bug, closing!
