### ISSUE TITLE
how does rho handle websocket

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#79]
or I guess in more general how does it handle Task[Response] ? As far as I can tell, it cannot compile if Task[Response] is provided directly to the dsl, e.g., 

    GET / "foo" +? param[Option[Int]]("bar") |>> { (bar: Option[Int]) => WS(Exchange(Process.constant(bar.getOrElse(-1)).map(b => Text(b.toString())).take(5), Process.halt)) }

    could not find implicit value for parameter hf: org.http4s.rho.bits.HListToFunc[shapeless.::[Int,shapeless.HNil],Int => scalaz.concurrent.Task[org.http4s.Response]]

**Comment by ShengC** [comment]
coming up with an ugly hack for websocket ...

     import org.http4s.server.websocket._
     import org.http4s.websocket.WebsocketBits._
      
     val src = Process.constant("test").toSource.zipWithIndex.map({ case (msg, i) => Text(s"$msg - $i") })take(20)
     val snk = Process.halt
     
     // unfortunately websocketkey and websocket case class are both defined in a protected scope that as a user cannot access
     val attrs = WS(Exchange(src, snk)).run.attributes.entries.toList
     attrs.foldLeft(NotImplemented("this is a websocket route"))(_.withAttribute(_))

Besides exposing too many internal logic, this solution does not allow response evaluated in a separate thread pool. In normal HttpService, I can use Task.fork to easily run the response in a different thread pool, but with rho dsl, there seems to be no easy to achieve the same effect.

**Comment by bryce-anderson** [comment]
I have given no consideration to websockets in rho as of yet.

The problem shouldn't be the `Task` but the `Response`: who deals in `Result`s to keep some compile time information around for use in swagger generation etc, which is just a wrapper around `Response` with some extra type information.

**Comment by bryce-anderson** [comment]
@ShengC, I have a PR to address this, but I'm not sure when it will hit a release. In the intrum, you could copy the [`ResultMatcher`](https://github.com/http4s/rho/commit/b61889ca6b804d289adb8f1c31971dc4bededbbb#diff-a25ac8cd537b220d5a74fd580617552cR442) code and bring the implicit into scope manually.

**Comment by ShengC** [comment]
@bryce-anderson,

I think I got what you mean. I have rewritten the hack, which now seems more reasonable ...
  
  Task.fork {
     import org.http4s.server.websocket._
     import org.http4s.websocket.WebsocketBits._
      
     val src = Process.constant("test").toSource.zipWithIndex.map({ case (msg, i) => Text(s"$msg - $i") })take(20)
     val snk = Process.halt
     
     WS(Exchange(src, snk)).flatMap(_.attributes.entries.foldLeft(NotImplemented("this is a websocket route"))(_.withAttribute(_)))
  }

**Comment by ShengC** [comment]
@bryce-anderson, yes that result matcher definitely is helpful :-)

**Comment by ShengC** [comment]
This raises another problem though. Look at this example,

    GET / "number" +? param[Int]("num") |?? { (num: Int) =>
      if (num < 0) BadRequest("num <= 0 :-(")
      else WS(Exchange(Process.constant("test").take(num).map(Text(_)), Process.halt))
    }

The implicits get messed up in this case, since `BadRequest` does not get resolved to a `Task[Response]`. The only workaround I have for this is to explicitly use `org.http4s.dsl.BadRequest(...)` so that an implicit `ResultMatcher[Response]` can be resolved. It is definitely an unpleasant hack, wondering if there is a more natural way to address this ?

**Comment by bryce-anderson** [comment]
There is no easy way to make the types unify there. What you've done is the best we can do with the current state of affairs. To make it better, rho will need to get a first class notion of `WS`.

**Comment by bryce-anderson** [comment]
I do remember another way you can make this work, but you lose any swagger information (if you were using it at all): try `BadRequest.pure("num <= 0 :-(")`. that will make a `Task[Response]` instead of a `Task[Result]` and will match the `WS` result type.

**Comment by ShengC** [comment]
Thanks :) Does swagger support websocket anyway ?

**Comment by bryce-anderson** [comment]
Nope.
