### ISSUE TITLE
weird parameter combination error

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#86]
// this compiles
      GET / root / "foo" +? param[Option[String]]("bar1") & param[Option[String]]("bar2") & param[Int]("bar3", -1) |>> { (request: org.http4s.Request, b1: Option[String], b2: Option[String], b3: Int) =>
        Ok("ok")
      }
  
      // this does not
      val params = param[Option[String]]("bar1") and param[Option[String]]("bar2") and param[Int]("bar3", -1)
      GET / root / "foo" +? params |>> { (request: org.http4s.Request, b1: Option[String], b2: Option[String], b3: Int) =>
        Ok("ok")
      }

What's the difference between the two ?

**Comment by bryce-anderson** [comment]
Indeed, that looks like it should compile. I'll look into it.

**Comment by bryce-anderson** [comment]
It looks to be a bad ordering of type parameters [here](https://github.com/http4s/rho/blob/master/core/src/main/scala/org/http4s/rho/bits/QueryAST.scala#L22) as compared to the correct and more common usage [here](https://github.com/http4s/rho/blob/master/core/src/main/scala/org/http4s/rho/QueryBuilder.scala#L26). Its also broken for the header rules in the same fashion. I'll have a PR to fix this soon; I just need to write a few tests for it.
