### ISSUE TITLE
how does rho generate swagger page for a custom param ?

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#89]
I have made up a `StringParser` to map a parameter (which is basically a json string) to a case class in one of the routes. Now I wish I can show in  `Swagger` page that one of the parameters for this rest api call should be that class. It seems like all param types that can be properly shown in `Swagger` page is defined as an instance of `rho.swagger.TypeBuilder.DataType` which unfortunately is a `sealed trait`. So the question is is it possible to show a custom param type in `Swagger` page at all ?

**Comment by ShengC** [comment]
Guess this would be more clear with an example

    case class Foo(x: Int, y: String)

    val fooParser = new StringParser[Foo] {
        override val typeTag: Some[TypeTag[Foo]] = Some(implicitly[TypeTag[Foo]])
        override def parse(s: String): ParserResult[Foo] = {
          scalaz.\/.fromTryCatchNonFatal(JsonMethods.parse(s).extract[Foo]) match {
            case scalaz.-\/(t) => ParserFailure(t.getMessage())
            case scalaz.\/-(t) => ParserSuccess(t)
          }
        }
     }    

in rho

    GET / "foo" +? param[Option[Foo]]("foo") |>> { (foo: Option[Foo]) =>  Ok(s"received $foo") }

although swagger.json shows for the `foo` route, it takes one parameter typed as `Foo`, but the swagger page just shows `undefined` type for this param. I think I probably need a custom `SwaggerFormats`. If yes, can you point to where I should start with ?

**Comment by bryce-anderson** [comment]
I _think_ it will be a bit more complex than adding a `SwaggerFormats`. I'm not sure the [`SwaggerModelBuilder`](https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala) is currently designed to look in the query or route for models.

**Comment by bryce-anderson** [comment]
I believe we can get this to work without too much pain: much like the [`collectResultTypes`](https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala#L54) and [`collectCodecTypes`](https://github.com/http4s/rho/blob/master/swagger/src/main/scala/org/http4s/rho/swagger/SwaggerModelsBuilder.scala#L60) methods, we need to extract the types from the query or elsewhere from which models may be hiding.

Unfortunately I won't be able to work on this in the short term.

**Comment by ShengC** [comment]
so I read the `QueryBuilder` and `SwaggerModelBuilder`, turns out there are a few things currently broken ... I will specify as follows,

1. `SwaggerModelBuilder` actually generates the `Foo` as for the `type` field for the `foo` param in `swagger.json`, but that's not enough. In order to render complex type, one has to define it in the `model` section. Take a look at this,
https://github.com/swagger-api/swagger-core/wiki/Datatypes

2. the `collection` type for `swagger` is not generated right.... So for instance in order to represent a collection of int as a type for a param, one has to use this syntax,

        "type": "array",
        "items": {
            "type": "integer"
        }

  instead of 

        "type": "List",
        "default": "List()"

  as what it is generated by the current code. Take a look at swagger specification,
  http://swagger.io/specification/

3. I'd like to have the description available for the param(s), which is a perfect way to illustrate a complex type for the user. See this example from specification page,

        {
          "name": "id",
          "in": "query",
          "description": "ID of the object to fetch",
          "required": false,
          "type": "array",
          "items": {
            "type": "string"
          },
          "collectionFormat": "multi"
        }

**Comment by ShengC** [comment]
I will work on it.

**Comment by bryce-anderson** [comment]
Closed via fc72df5e884b6f5da054b54360a373cd6925a283.
