### ISSUE TITLE
how to compose two rho services ...

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#90]
object A extends RhoService {
      GET / "ping" |>> { Ok("pong") }
    }

    object B extends RhoService {
     GET / "pong" |>> { Ok("ping") }
    }

with `A.toService orElse B.toService` mounted, `swagger` page only shows method in `A`, if `mount(A.toService)` and then `mount(B.toService)`, `swagger` page only shows method in `B`

**Comment by bryce-anderson** [comment]
Indeed, check out rho #48.
