### ISSUE TITLE
rho depends on http4s-server 0.7.0

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#92]
both latest release artifact 0.5.0 and snapshot 0.6.0-SNAPSHOT do. However the latest release artifact of http4s-server is 0.8.4, and its latest snapshot is 0.9.0-SNAPSHOT,

https://oss.sonatype.org/content/repositories/snapshots/org/http4s/rho-core_2.11/0.6.0-SNAPSHOT/rho-core_2.11-0.6.0-SNAPSHOT.pom
https://oss.sonatype.org/content/repositories/releases/org/http4s/rho-core_2.11/0.5.0/rho-core_2.11-0.5.0.pom

Is there a particular reason of doing so ?

**Comment by bryce-anderson** [comment]
As far as rho is concerned, 0.7.x and 0.8.x are compatible. We could change the snapshot now: http4s 0.9 has a few changes that will certainly effect rho.

**Comment by ShengC** [comment]
`sbt` is smart enough to pick the latest version across direct and transitive dependencies. However if someones uses `ivy` to resolve `http4s 0.8.4` and `rho 0.5.0`, he would unfortunately end up with two different versions of `http4s-server` in the dependencies. Therefore definitely I would make `http4s-server 0.8.4 `as the dependency for next release of `rho`, and `http4s-server 0.8.5-SNAPSHOT` as the dependency for the current `rho` snapshot build.

**Comment by ShengC** [comment]
Close as master depends on `http4s` 0.9 now.
