### ISSUE TITLE
`HListFunc` only allows function with up to 8 inputs

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#93]
Can we just change `MatcherHListToFunc` from `private` to `public` ... ? In my use case, I need to pass in more than 8 inputs for the route, and have to extend `HListFunc` to add an implicit to deal with that. Since `MatcherHListToFunc` is `private`, I have to copy that over, which is kind of awkward.

**Comment by ShengC** [comment]
As a side note - why not just use `pattern match` in `HListFunc` to extract the inputs? 

http://stackoverflow.com/questions/18468606/extractor-for-a-shapeless-hlist-that-mimics-parser-concatenation

**Comment by bryce-anderson** [comment]
Sure, changing `MatcherHListToFunc` from `private` to `public` seems OK to me. It is an implementation detail, so we should put a 'not necessarily stable' warning on it.
If you don't mind me asking, how many inputs do you have? That section of code could probably be generated by the build, but that might be more effort than its worth. Additionally, if you create deeper matchers I think they would be welcome here.

There is also a chance there are some functions in shapeless that could do this grunt work for us: https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/ops/functions.scala#L29.

From the link your provided, it would seem that using a pattern match will go through a lot of temporary objects which I would like to avoid, though I've not given it a thorough read. There is a good chance the ops functions I've linked to would suffer from the same problem.

**Comment by ShengC** [comment]
I have one route takes 9 inputs, and another takes 10 inputs. Since input can be in the form of `query`, `header` or `path`, I would not be surprised if other folks run into the same issue. 

There is a chance proposal from that link might already be part of `shapeless` given it was 2 years ago, but I might be wrong. Memory footprints might be a problem, but besides that, I don't have a idea of how to make it better.

**Comment by ShengC** [comment]
I've been following Miles' talk and `shapeless` for a while, and realize there actually might be a way to scrap away these boilerplates with something like this,

    import shapeless._
    import shapeless.ops.function._
    import shapeless.syntax.std.function._  

    implicit def instance[T <: HList, F, R](implicit m: ResultMatcher[R], fp: FnToProduct.Aux[F, T => R]): HListToFunc[T, F] = new MatcherHListToFunc[T, F] {
      override def matcher = m
      override def conv(f: F) = (req: Request, hh: T) => {
        m.conv(req, f.toProduct(hh))
      }
    }
    
    implicit def instance1[T <: HList, F, R](implicit m: ResultMatcher[R], fp: FnToProduct.Aux[F, Request :: T => R]): HListToFunc[T, F] = new MatcherHListToFunc[T, F] {
      override def matcher = m
      override def conv(f: F) = (req: Request, hh: T) => {
        m.conv(req, f.toProduct(req :: hh))
      }
    }

Of course this code should be put into the companion object to facilitate implicit resolution. I just had time to use `implicitly` to play with a few toy cases, and it seemed working. The key idea is to rely on implicit `FnToProduct` to let `F` take `HList` as input, so that we don't need to manually do the conversion. Also this should take no more than 22 inputs, as that is the upper bound of the `Product` trait.

**Comment by bryce-anderson** [comment]
I learned about those parts of shapeless after the boilerplate was already made so I didn't think much of it. If you get a PR together I'm sure we can get it merged.

**Comment by ShengC** [comment]
Have had some fun with `shapeless` today, and eventually the generic implicit worked and all routes of the example code compiled. Will run the unit tests tonight at home, if that does not throw any error either, will create a PR.

**Comment by bryce-anderson** [comment]
Awesome. It looks like the `Aux` types are all generated by sbt and use pattern matching. I don't think this will be a problem for performance, but I'm open to hearing otherwise. If it goes poorly it could lead to a lot of `Some` instances, or it could be distilled to what I've basically hard coded.

**Comment by ShengC** [comment]
I feel that `Aux` type in `shapeless` are basically to derive an isomorphism conversion between a composed type and an `HList` (and/or `Coproducts`). `shapeless` heavily uses the `macro` to make the conversion as generic as possible. It does come at the expense of compile time as a result, but I remember Miles mentioned the runtime cost was very little (in his presentation in this yr's scaladays).
