### ISSUE TITLE
`apiPath` in `SwaggerSupport` should be given a more general type

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#95]
It is currently of the type `String`, which prevents the user overriding `GET` of `swagger.json` to the `path` like,

    GET / "foo" / "swagger.json"

I think it should be of the type `PathRoute` or `PathRule`

**Comment by bryce-anderson** [comment]
Is this something you would like to get in before doing a release against http4s-0.9.0?

**Comment by ShengC** [comment]
that's ok - I am always developing against the `snapshot` :-) this can wait a little bit

**Comment by ShengC** [comment]
I think apiPath in `SwaggerSupport` should be given an explicit type `PathAST.TypedPath[shapeless.HNil]`. Implicit will coerce the type conversion in case a string is provided. This way user is able to override the swagger.json path to other path like `foo/bar/swagger.json`
