### ISSUE TITLE
`captureMap` causes `internal server error` when `f` throws exception

### ISSUE THREAD

**Issue by ShengC** [http4s/rho#99]
The right behavior should be sending back `Bad Request` with the reason. I believe this is also an issue for `existsAnd`. We need to wrap a `scala.Try` or `Scalaz.\/` when evaluating `f`

      case HeaderExists(key, f) => req.headers.get(key) match {
        case Some(h) => f(h).fold[ResultResponse[HList]](SuccessResponse(stack))(f => FailureResponse.result(f))

      case HeaderCapture(key, f, default) => req.headers.get(key) match {
        case Some(h) =>
          f(h).fold(f => FailureResponse.result(f), r => SuccessResponse(r::stack))

**Comment by bryce-anderson** [comment]
:+1:
